name: docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build_and_push_docker:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: setup registry
        uses: docker/login-action@v1 
        with:
          registry: registry.centralhardware.synology.me
          username: username 
          password: password
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: registry.centralhardware.synology.me/registry.centralhardware.ru/inventory-backend
